project/MisCosas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('css', views.css,name='css'),
    path('register/', views.register, name='register'),
    path('logout/',views.logout_view, name='logout'),
    path('user/<str:llave>',views.user, name='user'),
    path('users/',views.users, name='users'),
    path('login/',views.login_view, name='login'),
    path('informacion/',views.informacion, name='informacion'),
    path('<str:llave1>/<str:llave2>', views.processalimentador, name= 'processalimentador'),
    path('<str:llave>/<str:llave1>/<str:llave2>/De-Seleccionar', views.borrarprincipal, name= 'borrarprincipal'),
    path('<str:llave>/<str:llave1>/<str:llave2>', views.processitem, name= 'processitem'),
    path('alimentadores/', views.alimentadores, name='alimentadores'),
    path('<str:llave>/<str:llave1>/<str:llave2>/<str:llave3>/votopositivo/', views.gestionvotos, name='gestionvotos'),
    path('<str:llave>/<str:llave1>/<str:llave2>/<str:llave3>/votonegativo/', views.gestionvotos, name='gestionvotos'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MisCosas/', include('MisCosas.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'MisCosas.views.page_not_found'

project/MisCosas/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Alimentador(models.Model):
    alimentadorId = models.CharField(max_length=64, default="")
    nombre = models.CharField(max_length=64, default="")
    enlace = models.CharField(max_length=64, default="")
    puntuacion = models.IntegerField(default=0)
    type = models.CharField(max_length=64,default="")
    pagPrincipal = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Item(models.Model):
    nombre = models.CharField(max_length=64, default="")
    enlace = models.CharField(max_length=64, default="yo ")
    itemId = models.CharField(max_length=64, default="")
    fotoItem = models.CharField(max_length=64, default="")
    descripcion = models.TextField(blank=False, default="")
    votosPositivos = models.IntegerField(default=0)
    votosNegativos = models.IntegerField(default=0)
    votosTotales = models.IntegerField(default=0)
    alimentador = models.ForeignKey(Alimentador, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Users(models.Model):
    username = models.CharField(max_length=64, default="")
    email = models.EmailField(max_length=64, default="")
    password = models.CharField(max_length=64, default="")
    image = models.ImageField(upload_to='Users', null=True, default="")

    tamañoletra = models.CharField(max_length=64, default="")
    estilo = models.CharField(max_length=64, default="")

    def __str__(self):
        return self.username + " " + self.email + " " + self.password


class Voto(models.Model):
    usuario = models.ForeignKey(Users, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    estado = models.CharField(max_length=64, default="")


class Comentario(models.Model):
    usuario = models.ForeignKey(Users, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    cuerpo = models.TextField(blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='Comments', null=True, default="")

project/MisCosas/forms.py
from django import forms

class LoginForm(forms.Form):
    Username = forms.CharField()
    Password = forms.CharField(max_length=32, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    Username = forms.CharField()
    Email = forms.EmailField()
    Password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    image = forms.ImageField(required=False)

class changePhoto(forms.Form):
    image = forms.ImageField()

class comentarioForm(forms.Form):
    comentario = forms.CharField()
    imagen = forms.ImageField(required=False)
"""
class YoutubeForm(forms.Form):
    id = forms.CharField()
    
class Reddit(forms.Form):
    Section = forms.CharField()
   
class LastFmForm(forms.Form):
"""

project/MisCosas/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate,login,logout
from django.utils import timezone
from .forms import LoginForm, RegisterForm, changePhoto, comentarioForm
from django.contrib.auth.models import User
from .models import Item,Alimentador, Comentario, Users, Voto
import urllib.request
from xml.sax import make_parser
from .parseyt import YTHandler
from .parseflickr import FlickrHandler
from .parselastfm import LastfmHandler
from .apikeys import LASTFM_APIKEY
from unidecode import unidecode
from django.core import serializers


# Create your views here.s
def index(request):
    paginaPrincipal = True
    form = LoginForm()

    alimentadoresYT = Alimentador.objects.filter(pagPrincipal=True,type="youtube")
    alimentadoresFR = Alimentador.objects.filter(pagPrincipal=True,type="flickr")
    alimentadoresLF = Alimentador.objects.filter(pagPrincipal=True,type="lastfm")

    items =Item.objects.all()
    for item in items:
        item.votosTotales = item.votosPositivos - item.votosNegativos
        item.save()

    itemsOrdenados = Item.objects.all().order_by('-votosTotales')[:10]

    context = {'paginaPrincipal': paginaPrincipal,
                'form': form,
               'alimentadoresYT': alimentadoresYT,
               'alimentadoresFR': alimentadoresFR,
               'alimentadoresLF': alimentadoresLF,
               'top10': itemsOrdenados}

    user = request.user.username
    if user:
        try:
            user = Users.objects.get(username=user)
        except Users.DoesNotExist:
            user = Users(username=user)
            user.save()
        votos = Voto.objects.filter(usuario=user).order_by('-id')[:5]
        context['itemsvotados'] = votos

    if request.method == "POST":
        action = request.POST['action']
        if action == "youtube":
            idchannel = request.POST['idyoutube']
            redireccion = "/MisCosas/youtube/" + idchannel
            return HttpResponseRedirect(redireccion)

        elif action == "flickr":
            idtag = request.POST['idflickr']
            idtag = unidecode(idtag)
            redireccion = "/MisCosas/flickr/" + idtag
            return redirect(redireccion)

        elif action == "lastfm":
            artist = request.POST['artistlast']
            artist = unidecode(artist)
            redireccion = "/MisCosas/lastfm/" + artist
            return redirect(redireccion)


    if request.method == "GET":
        format = request.GET.get('format')
        if format == 'xml':
            return render(request, 'MisCosas/index.xml', context, content_type='text/xml')
        if format == 'json':
            list = [*itemsOrdenados, *alimentadoresYT, *alimentadoresFR,*alimentadoresLF]
            if user:
                list = [*itemsOrdenados,*votos, *alimentadoresYT, *alimentadoresFR, *alimentadoresLF]
            lista = serializers.serialize('json', list)
            return HttpResponse(lista, content_type="application/json")
    return render(request, 'MisCosas/index.html', context)

def alimentadores(request):
    form=LoginForm
    paginaAlimentadores = True
    try:
        alimentadoresYT = Alimentador.objects.filter(type="youtube")
        alimentadoresFR = Alimentador.objects.filter(type="flickr")
        alimentadoresLF = Alimentador.objects.filter(type="lastfm")

        context = {'alimentadoryoutube': alimentadoresYT,
                   'alimentadoresflickr':alimentadoresFR,
                   'alimentadoreslast':alimentadoresLF,
                   'paginaAlimentadores':paginaAlimentadores,
                   'form': form}

    except Alimentador.DoesNotExist:
        context = {}

    if request.method == "GET":
        format = request.GET.get('format')
        if format == 'xml':
            return render(request, 'MisCosas/alimentadores.xml', context, content_type='text/xml')
        if format == 'json':
            list = [*alimentadoresYT, *alimentadoresFR, *alimentadoresLF]
            lista = serializers.serialize('json', list)
            return HttpResponse(lista, content_type="application/json")

    return render(request,'MisCosas/alimentadores.html',context)

def borrarprincipal(request, llave, llave1,llave2 ):
    if llave == 'flickr':
        llaveTraducida = llave1.replace(" ","").lower()
        a = Alimentador.objects.get(alimentadorId=llaveTraducida)
    else:
        a = Alimentador.objects.get(alimentadorId=llave1)

    a.pagPrincipal = not a.pagPrincipal
    a.save()
    if llave2 == "paginaPrincipal":
        redireccion = "/MisCosas/"
    elif llave2  == "paginaAlimentador":
        redireccion = "/MisCosas/"+ llave + "/" + llave1

    return redirect(redireccion)

def processalimentador(request, llave1, llave2):
    Parser = make_parser()
    if llave1 == 'youtube':
        Parser.setContentHandler(YTHandler())
        url = 'https://www.youtube.com/feeds/videos.xml?channel_id=' \
            + llave2

    if llave1 == 'flickr':
        llave2 = llave2.replace(" ", "%20") # Convierto los espacios en %20 para que se pueda parsear
        Parser.setContentHandler(FlickrHandler())
        url = 'https://www.flickr.com/services/feeds/photos_public.gne?tags=' \
              + llave2
        llave2 = llave2.replace("%20", "").lower() # convierto el título en la llave que siempre se hace quitando los espacios y en minuscula

    if llave1 == 'lastfm':
        llavetraducida = llave2.replace(" ", "%20")
        Parser.setContentHandler(LastfmHandler())
        url = 'http://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=' + llavetraducida + '&api_key=' + LASTFM_APIKEY

    try:
        xmlStream = urllib.request.urlopen(url)
        Parser.parse(xmlStream)
    except:
        return render(request, 'MisCosas/404.html', {})
    try:
        a = Alimentador.objects.get(alimentadorId=llave2)
    except:
        return render(request, 'MisCosas/404.html', {})

    items = Item.objects.filter(alimentador=a)

    for item in items:
        item.votosTotales = item.votosPositivos - item.votosNegativos
        item.save()

    form= LoginForm();
    context = {'contentList': items,
               'alimentador': a,
               'form':form}

    if request.method == "GET":
        format = request.GET.get('format')
        if format == 'xml':
            return render(request, 'MisCosas/alimentador.xml', context, content_type='text/xml')
        if format == 'json':
            list = [a, *items]
            lista = serializers.serialize('json', list)
            return HttpResponse(lista, content_type="application/json")

    return render(request, 'MisCosas/alimentador.html', context)

def processitem(request, llave,llave1, llave2):

    a = Alimentador.objects.get(alimentadorId=llave1)
    i = Item.objects.get(itemId=llave2)
    form = LoginForm()

    context = {'alimentador': a,
               'item': i,
               'form': form}

    user = request.user.username
    if user:
        user = Users.objects.get(username=user)
        context['users'] = user
        context['form2'] = comentarioForm()
        form = comentarioForm(request.POST, request.FILES)
        if form.is_valid():
            cuerpo = form.cleaned_data['comentario']
            imagen = form.cleaned_data['imagen']
            c = Comentario(usuario=user, fecha=timezone.now(), cuerpo=cuerpo, item=i, imagen=imagen)
            c.save()
        try:
            voto = Voto.objects.get(usuario=user, item=i)
            context['voto'] = voto
        except Voto.DoesNotExist:
            print("no votes")

    try:
        comments = Comentario.objects.filter(item__itemId=llave2)
        context['comment'] = comments
    except Comentario.DoesNotExist:
        print("No Comments")

    if request.method == "GET":
        format = request.GET.get('format')
        if format == 'xml':
            return render(request, 'MisCosas/item.xml', context, content_type='text/xml')
        if format == 'json':
            list = [a, i]
            if user:
                list = [a, i,*comments]
            lista = serializers.serialize('json', list)
            return HttpResponse(lista, content_type="application/json")
    return render(request, 'MisCosas/item.html',context)

def gestionvotos(request,llave, llave1,llave2,llave3):
    i = Item.objects.get(itemId=llave2)
    name = request.user.username
    if name:
        action = request.POST.get('action', None)
        u = Users.objects.get(username=name)

        if action == "votopositivo":
            try:
                v = Voto.objects.get(usuario=u, item=i)
                if v.estado == "estadonegativo":
                    i.votosPositivos = i.votosPositivos + 1
                    i.votosNegativos = i.votosNegativos - 1
                    i.save()
                v.estado = "estadopositivo"
                v.save()
            except Voto.DoesNotExist:
                i.votosPositivos = i.votosPositivos + 1
                i.save()
                v = Voto(usuario=u, item=i, estado="estadopositivo")
                v.save()

        elif action =="votonegativo":
            try:
                v = Voto.objects.get(usuario=u, item=i)
                if v.estado == "estadopositivo":
                    i.votosPositivos = i.votosPositivos - 1
                    i.votosNegativos = i.votosNegativos + 1
                    i.save()
                v.estado = "estadonegativo"
                v.save()
            except Voto.DoesNotExist:
                i.votosNegativos = i.votosNegativos + 1
                i.save()
                v = Voto(usuario=u, item=i, estado="estadonegativo")
                v.save()

        a = Alimentador.objects.get(alimentadorId=llave1)
        items = Item.objects.filter(alimentador=a)
        votospos = 0
        votosne = 0
        for votos in items:
            votospos = votos.votosPositivos + votospos

project/MisCosas/templates/MisCosas/alimentador.html
{% extends 'MisCosas/base.html' %}
    {% block contenido %}

    <header id="alimentador">
        {%if alimentador.type == 'youtube'%}
            <h2 class="youtube"><i class="fab fa-youtube"></i>Youtube</h2>
        {%elif alimentador.type == 'flickr'%}
            <h2 class="flickr"><i class="fab fa-flickr"></i>Flickr</h2>
        {%elif alimentador.type == 'lastfm'%}
            <h2 class="lastfm">L<i class="fab fa-lastfm"></i>t.fm</h2>
        {%endif%}
        <h1><a href="{{alimentador.enlace}}">{{alimentador.nombre}}</a></h1>
        <div class="col-sm-4 offset-sm-4">
            {%if alimentador.type == 'youtube'%}
            <form action="{{alimentador.alimentadorId}}/paginaAlimentador/De-Seleccionar" method="POST">
            {%elif alimentador.type == 'flickr' or alimentador.type == 'lastfm' %}
            <form action="{{alimentador.nombre}}/paginaAlimentador/De-Seleccionar" method="POST">
            {%endif%}
                {% csrf_token %}
                {%if alimentador.pagPrincipal%}
                <button type="submit" class="btn btn-primary">Deselecionar</button>
                {%else%}
                <button type="submit" class="btn btn-primary">Seleccionar</button>
                {%endif%}
            </form>
        </div>
        <div class="row">
            <div class="col-sm-3 offset-9 actualizar">
                <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary ">Actualizar</button>
                </form>
            </div>
        </div>
    </header>
    <p></p>
    {% if contentList %}
    <div class="row" id="informacionalimentador">
        {% for content in contentList %}
            <div class="col col-sm-3">
                <section class="alim">
                    <h5 class="nombreitem">
                        <a href="{{content.enlace}}">{{content.nombre}}</a><br>
                    </h5>
                    <a class="enlaceitem" href="{{alimentador.alimentadorId}}/{{content.itemId}}">Más información ></a>
                </section>
                <br>
            </div>
        {% endfor %}
    </div>

    <p></p>

    {% else %}
    <p>No contents are available.</p>
    {% endif %}

    {%endblock%}

project/MisCosas/templates/MisCosas/alimentadores.html
{% extends 'MisCosas/base.html' %}
    {% block contenido %}

    <header id="ali">
        <h1>Alimentadores</h1>
    </header>

    <p></p>

    <div class="container-fluid">

        <div class="row infoalimentadores text-center">
            <div class="col col-md-6">
                <section id="youtube">
                    <h6>Alimentador</h6>
                    <h1 class="youtube"><i class="fab fa-youtube"></i>Youtube</h1>
                    <p>Aqui encontrarás la lista de alimentadores de youtube que se han utilizado alguna vez</p>
                    <p><a data-toggle="collapse" data-target="#alimentadoresyoutube" href="#">Mostrar > </a></p>

                    <div id="alimentadoresyoutube" class="collapse">
                        <br>
                        {% for alimentadorYT in alimentadoryoutube %}
                        <h2 class="nombreitem">
                        <a href="{{alimentadorYT.enlace}}">{{alimentadorYT.nombre}}</a><br>
                        </h2>
                        <div class="row puntuacion">
                            <div class="col col-sm-6">
                                <h4>Items</h4>
                                <h6>{{alimentadorYT.item_set.count}}</h6>
                            </div>
                            <div class="col col-sm-">
                                <h4>Puntuación</h4>
                                <h6>{{alimentadorYT.puntuacion}}</h6>
                            </div>
                        </div>
                            <p>
                                <a class="enlaceitem" href="/MisCosas/youtube/{{alimentadorYT.alimentadorId}}">Más información ></a>
                            </p><br>
                            <br>
                            <br>
                        {% endfor %}
                    </div>
                 </section>
            </div>
            <div class="col col-md-6">
                <section id="flickr">
                <h6>Alimentador</h6>

                <h1 class="flickr"><i class="fab fa-flickr"></i>Flickr</h1>
                <p>Aqui encontrarás la lista de alimentadores de flickr que se han utilizado alguna vez</p>
                <p><a data-toggle="collapse" data-target="#alimentadoresflickr" href="#">Mostrar > </a></p>
                <div id="alimentadoresflickr" class="collapse">
                    <br>
                    {% for alimentadorFR in alimentadoresflickr %}
                    <h2 class="nombreitem">
                    <a href="{{alimentadorFR.enlace}}">{{alimentadorFR.nombre}}</a><br>
                    </h2>
                    <div class="row puntuacion">
                        <div class=" col col-sm-6">
                            <h4>Items</h4>
                            <h6>{{alimentadorFR.item_set.count}}</h6>
                        </div>
                        <div class="col col-sm-6">
                            <h4>Puntuación</h4>
                            <h6>{{alimentadorFR.puntuacion}}</h6>
                        </div>
                    </div>
                        <p>
                            <a class="enlaceitem" href="/MisCosas/{{alimentadorFR.type}}/{{alimentadorFR.nombre}}">Mas información ></a><br>
                        </p>
                        <br>
                        <br>
                    {% endfor %}
                </div>
                </section>
            </div>
        </div>
        <p></p>
        <div class="row infoalimentadores text-center">
            <div class="col-sm-6 offset-sm-3">
                <section id="lastfm">
                <h6>Alimentador</h6>

                <h1 class="lastfm">L<i class="fab fa-lastfm"></i>t.fm</h1>
                <p>Aqui econtrarás la lista de alimentadores de last.fm que se han utilizado alguna vez</p>
                <p><a data-toggle="collapse" data-target="#alimentadoreslast" href="#">Mostrar > </a></p>
                <div id="alimentadoreslast" class="collapse">
                    <br>
                    {% for alimentadorLF in alimentadoreslast %}
                    <h2 class="nombreitem">
                    <a href="{{alimentadorLF.enlace}}">{{alimentadorLF.nombre}}</a><br>
                    </h2>
                    <div class="row puntuacion">
                        <div class=" col col-sm-6">
                            <h4>Items</h4>
                            <h6>{{alimentadorLF.item_set.count}}</h6>
                        </div>
                        <div class="col col-sm-6">
                            <h4>Puntuación</h4>
                            <h6>{{alimentadorLF.puntuacion}}</h6>
                        </div>
                    </div>
                        <p>
                            <a class="enlaceitem" href="/MisCosas/{{alimentadorLF.type}}/{{alimentadorLF.nombre}}">Mas información ></a><br>
                        </p>
                        <br>
                        <br>
                    {% endfor %}
                </div>
                </section>
            </div>
        </div>
    </div>
    <p></p>

    {%endblock%}

project/MisCosas/templates/MisCosas/item.html
{% extends 'MisCosas/base.html' %}
    {% block contenido %}
    {%if alimentador.type == 'youtube'%}
        <header id="itemyou">
    {%elif alimentador.type == 'flickr'%}
        <header id="itemfr">
     {%elif alimentador.type == 'lastfm'%}
        <header id="itemlf">
    {%endif%}
        {%if alimentador.type == 'youtube'%}
            <h3><i class="fab fa-youtube"></i>Youtube</h3>
        {%elif alimentador.type == 'flickr'%}
            <h3><i class="fab fa-flickr"></i>Flickr</h3>
        {%elif alimentador.type == 'lastfm'%}
            <h3>l<i class="fab fa-lastfm"></i>t.fm</h3>
        {%endif%}
        <h1><a href="{{item.enlace}}">{{item.nombre}}</a></h1>
        <div class="row">
            <div class="col-sm-3 offset-sm-3">
                <h2><i class="fas fa-thumbs-up fa-2x"></i></h2>
                <h2>{{item.votosPositivos}}</h2>
            </div>
            <div class="col col-sm-3">
                <h2><i class="fas fa-thumbs-down fa-2x"></i></h2>
                <h2>{{item.votosNegativos}}</h2>
            </div>
        </div>
        <br>
        {% if user.is_authenticated %}
         <h3>¿Te gusta la página?</h3>
        <div class="row botonesvotos">
            <div class="col-sm-2 offset-sm-4 ">
                    <form action="{{item.itemId}}/paginaItem/votopositivo/" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary-outline botonitem" name="action" value="votopositivo"><i class="fas fa-thumbs-up fa-2x"></i></button>
                </form>
            </div>
            <div class="col col-sm-2 ">
                    <form action="{{item.itemId}}/paginaItem/votonegativo/" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary-outline botonitem" name="action" value="votonegativo"><i class="fas fa-thumbs-down fa-2x"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row botonesvotos">
            {%if voto.estado == 'estadopositivo'%}
            <div class="col-sm-2 offset-sm-4 ">
                <h4><i class="far fa-check-circle"></i></h4>
            </div>
            {%elif voto.estado == "estadonegativo"%}
            <div class="col-sm-2 offset-sm-6 ">
                 <h4><i class="far fa-check-circle"></i></h4>
            </div>
            {%endif%}
        </div>
        {%endif%}
    </header>
            <p></p>
    <section >
        {%if alimentador.type == 'youtube'%}
            <div class="row" id="itemsection">
                <div class="col col-sm-6">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/{{item.itemId}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <div class="col col-sm-6">
                    <h1>Descripción</h1>
                    <p>{{item.descripcion}}</p>
                </div>
            </div>
        {%elif alimentador.type == 'flickr'%}
            <div class="row justify-content-center " id="itemsection">
                <img src="{{item.fotoItem}}" class="text-center">
            </div>
        {%elif alimentador.type == 'lastfm'%}
            <div class="row justify-content-center " id="itemsection">
                <div class="col col-sm-6">
                    <h1>Portada del album</h1>
                </div>
                <div class="col col-sm-6">
                    <img src="{{item.fotoItem}}" class="text-center" width="300px">
                </div>

            </div>
        {%endif%}
    </section>
    <p></p>
    <section >
         <div class="row" id="itemalimentador">
                <div class="col col-sm-6">
                    <h5>Este ítem pertenece a</h5>
                    <h1><a href="{{alimentador.enlace}}">{{alimentador.nombre}}</a></h1>
                    {%if alimentador.type == 'youtube'%}
                    <form action="/MisCosas/{{alimentador.type}}/{{alimentador.alimentadorId}}" method="POST">
                    {%elif alimentador.type == 'flickr' or alimentador.type == 'lastfm' %}
                    <form action="/MisCosas/{{alimentador.type}}/{{alimentador.nombre}}" method="POST">
                    {%endif%}
                    {% csrf_token %}
                    <h2 class="nombreitem">
                        <button id="boton01" class="btn" name="action" value="{{content.nombre}}">Alimentador</button>
                    </h2>
                    </form>
                </div>
                <div class="col col-sm-3">
                    <h2>Items</h2>
                    <h5>{{alimentador.item_set.count}}</h5>
                </div>
                <div class="col col-sm-3">
                    <h2>Puntuación</h2>
                    <h5>{{alimentador.puntuacion}}</h5>
                </div>
        </div>
    </section>
    <br>
    <section id="itemscomments">
        <h2><i class="fas fa-comment"></i></h2>
        <h1>Comentarios</h1>
        <div class="row">
            <div class="col-sm-8 offset-sm-2">
                {%if comment%}
                {%for comentario in comment%}
                {%if comentario.usuario.image%}
                <h2> <img  class="" src="{{comentario.usuario.image.url}}" width="80">{{comentario.usuario.username}}</h2>
                {%else%}
                <h2><i class="fas fa-user"></i>&nbsp&nbsp{{comentario.usuario.username}}</h2>
                {%endif%}
                <h4>{{comentario.fecha}}</h4>
                {%if comentario.imagen%}
                <div class="row align-items-center">
                    <div class="col-sm-3 offset-sm-3">
                        <p>{{comentario.cuerpo}}</p>
                    </div>
                    <div class="col-sm-3">
                        <img  class="" src="{{comentario.imagen.url}}"  width="80">
                    </div>
                </div>

                {%else%}
                <p>{{comentario.cuerpo}}</p>
                {%endif%}
                <hr>
                {%endfor%}

                {%else%}
                    <h4>No Comments</h4>
                {%endif%}
                <br>

                {% if user.is_authenticated %}
                <h3>Nuevo comentario</h3>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form2.as_p}}
                    <button type="submit" class="btn btn-primary" name="action" value="comment">Enviar</button>
                </form>
            </div>
                {%endif%}
        </div>

    </section>
    {%endblock%}

project/MisCosas/templates/MisCosas/register.html
{% extends 'MisCosas/base.html' %}

    {% block contenido %}
    <header class="register">
        <h1> Crea tu usuario</h1>
    </header>
    <div class="container" id="register-form">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <form method="POST" action="" class="form-group" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="save btn btn-info">Crear</button>
                </form>
                {%if error%}
                <p>{{error}}</p>
                {%endif%}
            </div>
        </div>

    </div>

    {%endblock%}

project/MisCosas/templates/MisCosas/users.html
{% extends 'MisCosas/base.html' %}

    {% block contenido %}
    <header id="headerusuarios">
        <h1>Usuarios</h1>
    </header>
    <section>
    <div class="row" id="usuario">
        {%for user in users%}
        <div class="col col-sm-3" id="tituloperfil">
            {%if user.image%}
                <img  class="fotouser" src="{{user.image.url}}" width="200" height="130"><br>
            {%else%}
                <div class=""><i class="fas fa-user fa-8x"></i></div>
            {%endif%}
            <p><a href="/MisCosas/user/{{user.username}}">{{user.username}}</a><br>
            Items votados:{{user.voto_set.count}}<br>
            Items comentados:{{user.comentario_set.count}}</p>
        </div>
        {%endfor%}
    </div>
    </section>
    <p></p>
    {% endblock %}